Atomtype:  C0
Density cutoff =  0.2375
Fitting points over the range  2.58  to  4.28
B (twopoint fit): 2.30900632935
B (average over range): 2.30925710843
Atomtype:  O1
Density cutoff =  0.2375
Fitting points over the range  2.78  to  4.44
B (twopoint fit): 2.49907259996
B (average over range): 2.49963357632
Atomtype:  O2
Density cutoff =  0.2375
Fitting points over the range  2.78  to  4.44
B (twopoint fit): 2.49953749584
B (average over range): 2.50009742624
