Atomtype:  O0
Density cutoff =  0.2375
Fitting points over the range  3.14  to  4.56
B (twopoint fit): 2.38587081499
B (average over range): 2.38619096552
Atomtype:  C1
Density cutoff =  0.2375
Fitting points over the range  4.46  to  8.4
B (twopoint fit): 1.87674848723
B (average over range): 1.87644160147
Atomtype:  C2
Density cutoff =  0.2375
Fitting points over the range  4.46  to  8.4
B (twopoint fit): 1.87660142049
B (average over range): 1.87629371561
Atomtype:  H3
Density cutoff =  0.2375
Fitting points over the range  4.36  to  8.62
B (twopoint fit): 1.9640795875
B (average over range): 1.96401793659
Atomtype:  H4
Density cutoff =  0.2375
Fitting points over the range  4.36  to  8.62
B (twopoint fit): 1.96397319042
B (average over range): 1.96391143517
Atomtype:  H5
Density cutoff =  0.2375
Fitting points over the range  4.2  to  8.5
B (twopoint fit): 1.92388108217
B (average over range): 1.92375539035
Atomtype:  H6
Density cutoff =  0.2375
Fitting points over the range  4.2  to  8.5
B (twopoint fit): 1.92387397161
B (average over range): 1.92374826361
Atomtype:  H7
Density cutoff =  0.2375
Fitting points over the range  4.2  to  8.5
B (twopoint fit): 1.92379980258
B (average over range): 1.92367401016
Atomtype:  H8
Density cutoff =  0.2375
Fitting points over the range  4.2  to  8.5
B (twopoint fit): 1.923786212
B (average over range): 1.92366038713
