Atomtype:  C0
Density cutoff =  0.2375
Fitting points over the range  4.4  to  8.26
B (twopoint fit): 1.82874364167
B (average over range): 1.8283223539
Atomtype:  C1
Density cutoff =  0.2375
Fitting points over the range  5.06  to  7.98
B (twopoint fit): 1.75123324819
B (average over range): 1.75020853338
Atomtype:  O2
Density cutoff =  0.2375
Fitting points over the range  2.94  to  4.34
B (twopoint fit): 2.33225004094
B (average over range): 2.33244924476
Atomtype:  H3
Density cutoff =  0.2375
Fitting points over the range  5.28  to  7.54
B (twopoint fit): 1.67189950428
B (average over range): 1.67053088469
Atomtype:  H4
Density cutoff =  0.2375
Fitting points over the range  4.66  to  8.42
B (twopoint fit): 1.88477421014
B (average over range): 1.88443806637
Atomtype:  H5
Density cutoff =  0.2375
Fitting points over the range  4.72  to  8.32
B (twopoint fit): 1.84806843795
B (average over range): 1.84758435466
Atomtype:  H6
Density cutoff =  0.2375
Fitting points over the range  4.72  to  8.32
B (twopoint fit): 1.84807036201
B (average over range): 1.84758628638
Atomtype:  H7
Density cutoff =  0.2375
Fitting points over the range  4.26  to  8.52
B (twopoint fit): 1.92775453114
B (average over range): 1.92762868645
Atomtype:  H8
Density cutoff =  0.2375
Fitting points over the range  4.26  to  8.52
B (twopoint fit): 1.92776206177
B (average over range): 1.92763623368
