Atomtype:  O0
Density cutoff =  0.2375
Fitting points over the range  2.98  to  6.2
B (twopoint fit): 2.25764352677
B (average over range): 2.25793858328
Atomtype:  H1
Density cutoff =  0.2375
Fitting points over the range  1.92  to  2.12
B (twopoint fit): 2.34880950387
B (average over range): 2.3485681289
Atomtype:  H2
Density cutoff =  0.2375
Fitting points over the range  1.92  to  2.12
B (twopoint fit): 2.34880924042
B (average over range): 2.34856787274
