Atomtype:  C0
Density cutoff =  0.2375
Fitting points over the range  4.64  to  8.38
B (twopoint fit): 1.86645374711
B (average over range): 1.8660573197
Atomtype:  N1
Density cutoff =  0.2375
Fitting points over the range  1.8  to  8.5
B (twopoint fit): 2.03284412914
B (average over range): 2.03323776082
Atomtype:  H2
Density cutoff =  0.2375
Fitting points over the range  1.3  to  9.06
B (twopoint fit): 2.22209664098
B (average over range): 2.22245771489
Atomtype:  H3
Density cutoff =  0.2375
Fitting points over the range  4.4  to  8.7
B (twopoint fit): 1.99492534817
B (average over range): 1.99492444123
Atomtype:  H4
Density cutoff =  0.2375
Fitting points over the range  4.4  to  8.7
B (twopoint fit): 1.99493637167
B (average over range): 1.99493549485
Atomtype:  H5
Density cutoff =  0.2375
Fitting points over the range  1.96  to  2.88
B (twopoint fit): 2.62817119039
B (average over range): 2.62799524202
Atomtype:  H6
Density cutoff =  0.2375
Fitting points over the range  1.96  to  2.88
B (twopoint fit): 2.62817176099
B (average over range): 2.62799579436
