Atomtype:  C0
Density cutoff =  0.2375
Fitting points over the range  1.96  to  8.42
B (twopoint fit): 1.95532349683
B (average over range): 1.95538752744
Atomtype:  H1
Density cutoff =  0.2375
Fitting points over the range  2.56  to  3.4
B (twopoint fit): 2.52642727827
B (average over range): 2.52647417877
Atomtype:  H2
Density cutoff =  0.2375
Fitting points over the range  2.56  to  3.4
B (twopoint fit): 2.5264260326
B (average over range): 2.52647294409
Atomtype:  H3
Density cutoff =  0.2375
Fitting points over the range  2.56  to  3.4
B (twopoint fit): 2.52642731519
B (average over range): 2.52647421296
Atomtype:  H4
Density cutoff =  0.2375
Fitting points over the range  2.56  to  3.4
B (twopoint fit): 2.52642350928
B (average over range): 2.52647044196
