Atomtype:  N0
Density cutoff =  0.2375
Fitting points over the range  1.74  to  8.42
B (twopoint fit): 1.9889506142
B (average over range): 1.98925673168
Atomtype:  H1
Density cutoff =  0.2375
Fitting points over the range  1.98  to  2.56
B (twopoint fit): 2.63378343343
B (average over range): 2.633543565
Atomtype:  H2
Density cutoff =  0.2375
Fitting points over the range  1.98  to  2.58
B (twopoint fit): 2.63160127387
B (average over range): 2.63135097879
Atomtype:  H3
Density cutoff =  0.2375
Fitting points over the range  1.98  to  2.58
B (twopoint fit): 2.63160137366
B (average over range): 2.63135108088
